version: '3.8'

services:
  dynamodb:
    container_name: dynamodb-reality-tv-voting-local
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    ports:
      - '8000:8000'
    volumes:
      - dynamodb-reality-tv-voting-data:/home/dynamodblocal

volumes:
  dynamodb-reality-tv-voting-data:
