service: serverless-reality-tv-voting
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-prune-plugin
  - serverless-plugin-lambda-insights
  # - serverless-newrelic-lambda-layers
  - serverless-dotenv-plugin
  - serverless-offline #needs to be last in the list

custom:
  esbuild:
    bundle: true
    minify: true
  # newRelic:
  #   accountId: ${self:provider.environment.NEW_RELIC_ACCOUNT_ID}
  #   apiKey: ${self:provider.environment.NEW_RELIC_API_KEY}
  #   debug: true
  #   enableExtension: true
  #   enableFunctionLogs: true
  #   enableIntegration: true
  #   logLevel: error

provider:
  ${file(./serverless.provider.yml):provider}

functions:
  ${file(./serverless.functions.yml):functions}

resources:
  ${file(./serverless.resources.yml):resources}