service: serverless-reality-tv-voting
frameworkVersion: '3'

plugins:
  - serverless-prune-plugin
  - serverless-plugin-lambda-insights
  - serverless-offline #needs to be last in the list

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  architecture: arm64
  memorySize: 128
  timeout: 30
  environment:
    AWS_REGION: us-east-1
    DYNAMODB_ENDPOINT: https://dynamodb.us-east-1.amazonaws.com
    DYNAMODB_TABLE_USERS: ${sls:stage}-users
    DYNAMODB_TABLE_PARTICIPANTS: ${sls:stage}-participants
    API_ZIPCODE_VIACEP_ENDPOINT: https://viacep.com.br/ws
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE_USERS}"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE_PARTICIPANTS}"

functions:
  users-create:
    handler: src/lambdas/users/users-create.create
    lambdaInsights: true
    events:
      - http:
          path: /users
          method: post

resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: documentNumber
            AttributeType: S
          -
            AttributeName: createdAt
            AttributeType: N
        KeySchema:
          -
            AttributeName: documentNumber
            KeyType: HASH
          -
            AttributeName: createdAt
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE_USERS}

    ParticipantsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: code
            AttributeType: S
          -
            AttributeName: createdAt
            AttributeType: N
        KeySchema:
          -
            AttributeName: code
            KeyType: HASH
          -
            AttributeName: createdAt
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE_PARTICIPANTS}