service: serverless-reality-tv-voting
frameworkVersion: '3'

plugins:
  - serverless-prune-plugin
  - serverless-plugin-lambda-insights
  - serverless-offline #needs to be last in the list

provider:
  ${file(./serverless.provider.yml):provider}

functions:
  ${file(./serverless.functions.yml):functions}

resources:
  ${file(./serverless.resources.yml):resources}