resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: documentNumber
            AttributeType: S
        KeySchema:
          -
            AttributeName: documentNumber
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE_USERS}

    ParticipantsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: code
            AttributeType: S
          -
            AttributeName: votes
            AttributeType: N
        KeySchema:
          -
            AttributeName: code
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: votes-index
            KeySchema:
            - AttributeName: code
              KeyType: HASH
            - AttributeName: votes
              KeyType: RANGE
            Projection:
              ProjectionType: ALL
        TableName: ${self:provider.environment.DYNAMODB_TABLE_PARTICIPANTS}